- name: Destroy cloud infrastructure
  hosts: localhost
  tasks:
    - name: Terminate EC2 instances
      ec2:
        region: "us-east-1"
        instance_ids: "{{ ec2_instance_ids }}"
        state: absent
      register: ec2_termination

    - name: Remove Docker container
      shell: "docker-compose down"
      args:
        chdir: /home/ubuntu/app

    - name: Remove Docker image
      shell: "docker rmi your_dockerhub_username/app:latest"
